name: Monitoring and Alerting

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  check_website:
    name: Monitoring and Alerting
    runs-on: ubuntu-latest

    steps:
    - name: Check if website is up
      run: |
        HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" https://felixhong0711.github.io/devops-project/)
        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "Website is down"
          exit 1
        else
          echo "Website is up"
        fi

    - name: Send email if website is down
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Website Down Alert"
        to: ${{ secrets.ALERT_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: "The website https://felixhong0711.github.io/devops-project/ is down."
